# https://github.com/axel-op/googlejavaformat-action

name: Format

on:
  push:
    branches:
      - translateComments

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      - uses: actions/setup-java@v1
        with:
          # Recommended: latest versions of Google Java Format require JDK 11+
          java-version: "11"
      - uses: axel-op/googlejavaformat-action@v3
